title: felipe melchior | hdrnn
author: Felipe Homrich Melchior
email: your-email@example.com
description: >
  estudos e write-ups de segurança da informação 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hdrnn.dev" 
github_username:  felipemelchior

# Build settings
theme: no-style-please
theme_config:
  appearence: "dark"
  back_home_text: '..'
  date_format: '%d-%m-%Y'
  show_description: false
plugins:
  - jekyll-feed

